2018-09-02 18:11:42,814 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:48]
2018-09-02 18:36:00,453 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:48]
2018-09-02 21:29:05,269 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:48]
2018-09-02 21:29:12,786 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:48]
2018-09-02 22:33:12,274 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:48]
2018-09-04 09:16:51,941 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:48]
2018-09-04 10:51:44,628 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:48]
2018-09-04 10:52:48,176 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:48]
2018-09-04 11:06:34,723 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:48]
2018-09-04 11:32:24,904 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:48]
2018-09-04 15:33:21,933 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:48]
2018-09-04 15:56:19,817 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:48]
2018-09-04 16:05:47,567 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:48]
2018-09-04 16:24:19,015 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:48]
2018-09-04 16:24:48,197 ERROR: Exception on /index [GET] [in /home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jpch89/code/microblog/app/routes.py", line 39, in index
    page, app.config['POST_PER_PAGE'], False)
KeyError: 'POST_PER_PAGE'
2018-09-04 16:24:53,374 ERROR: Exception on /index [GET] [in /home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jpch89/code/microblog/app/routes.py", line 39, in index
    page, app.config['POST_PER_PAGE'], False)
KeyError: 'POST_PER_PAGE'
2018-09-04 16:24:54,664 ERROR: Exception on /index [GET] [in /home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jpch89/code/microblog/app/routes.py", line 39, in index
    page, app.config['POST_PER_PAGE'], False)
KeyError: 'POST_PER_PAGE'
2018-09-04 16:24:56,229 ERROR: Exception on /explore [GET] [in /home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jpch89/code/microblog/app/routes.py", line 149, in explore
    page, app.config['POST_PER_PAGE'], False)
KeyError: 'POST_PER_PAGE'
2018-09-04 16:25:10,738 ERROR: Exception on /index [GET] [in /home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jpch89/code/microblog/app/routes.py", line 39, in index
    page, app.config['POST_PER_PAGE'], False)
KeyError: 'POST_PER_PAGE'
2018-09-04 16:32:07,929 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:48]
2018-09-04 17:08:05,029 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:48]
2018-09-04 18:22:24,542 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:50]
2018-09-04 18:30:36,514 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:50]
2018-09-04 20:58:16,783 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:50]
2018-09-04 21:18:57,997 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:50]
2018-09-05 09:52:00,519 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:50]
