2018-09-08 09:41:05,187 ERROR: Exception on / [GET] [in /home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/jpch89/code/microblog/app/routes.py", line 55, in index
    next_url=next_url, prev_url=prev_url)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jpch89/code/microblog/app/templates/_post.html", line 30, in template
    {{ _('翻译') }}
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/jpch89/code/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/jpch89/code/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/jpch89/code/microblog/app/templates/base.html", line 53, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/jpch89/code/microblog/app/templates/index.html", line 12, in block "app_content"
    {% include '_post.html' %}
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jpch89/code/microblog/app/templates/_post.html", line 30, in template
    {{ _('翻译') }}
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 213, in parse_if
    'name:endif'))
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2018-09-08 09:42:10,149 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 09:44:33,449 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:13:41,259 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:14:11,441 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:14:22,423 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:20:26,765 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:26:02,064 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:27:58,615 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:40:47,407 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:44:22,995 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:44:32,661 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:46:09,954 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:46:14,359 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:47:42,670 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:50:38,841 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:51:04,072 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:52:13,513 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:53:56,491 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:56:25,207 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 10:56:50,320 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 11:01:56,240 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 11:03:52,548 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 11:06:23,044 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 11:07:11,400 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 11:11:34,592 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 11:11:41,341 ERROR: Exception on /index [GET] [in /home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/home/jpch89/code/microblog/app/routes.py", line 28, in before_request
    g.locale = str(get_locale())
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/flask_babel/__init__.py", line 261, in get_locale
    locale = Locale.parse(rv)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/babel/core.py", line 268, in parse
    parts = parse_locale(identifier, sep=sep)
  File "/home/jpch89/code/microblog/venv/lib/python3.6/site-packages/babel/core.py", line 1094, in parse_locale
    raise ValueError('expected only letters, got %r' % lang)
ValueError: expected only letters, got 'zh-cn'
2018-09-08 11:13:36,949 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
2018-09-08 11:14:08,591 INFO: Microblog startup [in /home/jpch89/code/microblog/app/__init__.py:57]
